<div id="mypassword">
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('id', 'formpassword');
$form->setAttribute('action', $this->url('kabinet_data',["action"=>"password"]));
/*переопределим формат ошибок*/
$helper = $this->formElementErrors();
$helper->setMessageOpenFormat('<div class="alert alert-danger" role="alert">');
$helper->setMessageSeparatorString('<br/>');
$helper->setMessageCloseString('</div>');

if ($this->alertMessage){
?>
<div class="alert alert-<?=$this->alert_type?>" role="alert"><?=$this->alertMessage;?></div>
<?php 
} ?>

<?=$this->form()->openTag($form);?>
  <div class="form-group row">
    <label for="name" class="col-sm-2 col-form-label">Новый пароль</label>
    <div class="col-sm-10">
        <?php
        $name = $form->get('password');
        echo $this->formElement($name);
        echo $this->formElementErrors($name);
        ?>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-10">
              <?=$this->formInput($form->get('submit')); ?>
    </div>
  </div>
<?= $this->formElement($form->get('security')) ?>
<?= $this->form()->closeTag() ?>
</div>
<script type="text/javascript">
$("#formpassword").on("submit",function(e){
    e.preventDefault();
$(this).ajaxSubmit({
                 target: '#mypassword'
            });
});
$('[type=password]').hidePassword(true);
</script>


