<div id="myprofile">
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('id', 'formprofile');
$form->setAttribute('action', $this->url('kabinet_data',["action"=>"profile"]));
/*переопределим формат ошибок*/
$helper = $this->formElementErrors();
$helper->setMessageOpenFormat('<div class="alert alert-danger" role="alert">');
$helper->setMessageSeparatorString('<br/>');
$helper->setMessageCloseString('</div>');

if ($this->alertMessage){
?>
<div class="alert alert-<?=$this->alert_type?>" role="alert"><?=$this->alertMessage;?></div>
<?php 
} ?>

<?=$this->form()->openTag($form);?>
  <div class="form-group row">
    <label for="login" class="col-sm-2 col-form-label">Логин</label>
    <div class="col-sm-10">
        <?php
        $name = $form->get('login');
        echo $this->formInput($name);
        echo $this->formElementErrors($name);
        ?>
    </div>
  </div>
  <div class="form-group row">
    <label for="name" class="col-sm-2 col-form-label">Имя</label>
    <div class="col-sm-10">
        <?php
        $name = $form->get('name');
        echo $this->formInput($name);
        echo $this->formElementErrors($name);
        ?>
    </div>
  </div>
  <div class="form-group row">
    <label for="full_name" class="col-sm-2 col-form-label">Ф.И.О.</label>
    <div class="col-sm-10">
        <?php
        $name = $form->get('full_name');
        echo $this->formInput($name);
        echo $this->formElementErrors($name);
        ?>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-10">
        <?=$this->formInput($form->get('logout')); ?>
        <?=$this->formInput($form->get('submit')); ?>
    </div>
  </div>
<?= $this->formElement($form->get('security')) ?>
<?= $this->form()->closeTag() ?>
</div>
<script type="text/javascript">
$("input[name=logout]").on("click",function(e){
document.location.href="<?=$this->url("logout")?>";
});
$("#formprofile").on("submit",function(e){
    e.preventDefault();
$(this).ajaxSubmit({
                 target: '#myprofile'
            });
});
</script>


