<?php


$this->headTitle('Сброс пароля');

$form->get('login')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Ваш E-mail'
    ]);

$form->get('submit')->setAttributes([
    'class'=>'btn btn-large btn-primary'
    ]);

$form->prepare();
?>

<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <?= $this->form()->openTag($form); ?>

        <h2>Сброс пароля</h2>
            <?php if ($Error){
            ?>
            <div class="alert alert-warning" role="alert"><?=$Error;?></div>
            <?php 
            } ?>
 <p>Пожалуйста, введите свой E-mail</p>
        <?= $this->formElement($form->get('login')); ?>
        <?= $this->formElementErrors($form->get('login')); ?>                              

        <?= $this->formElement($form->get('captcha')); ?>
        <?= $this->formElementErrors($form->get('captcha')); ?>
<br>
        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
