<?php

$form->get('login')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Email address',
    'required' => true,
    'autofocus' => true
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);

$form->get('submit')->setAttributes([
    'class'=>'btn btn-lg btn-primary btn-block', 
    ]);

$form->get('password')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Password',
    'required' => true,
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);
?>

<div class="row">
    <div class="col-md-offset-4 col-md-3">
        <form class="form-signin" method="post">
            <h2 class="form-signin-heading">Пожалуйста, войдите</h2>
            <?php if ($isLoginError){
            ?>
            <div class="alert alert-warning" role="alert">
                Неверный логин/пароль. 
                <a href="<?= $this->url('reset-password') ?>">Забыли пароль?</a>
            </div>
            <?php 
            } ?>
            <?= $this->formLabel($form->get('login')); ?>
            <?= $this->formElement($form->get('login')); ?>
            <?= $this->formLabel($form->get('password')); ?>
            <?= $this->formElement($form->get('password')); ?>
            <div class="checkbox">
                <label>
                    <?= $this->formElement($form->get('remember_me')); ?> Запомнить меня
                </label>
            </div>

            <?= $this->formElement($form->get('csrf')) ?>
            <?= $this->FormButton($form->get('submit')); ?>

        </form>
    </div>
</div>