<div id="mylogin">
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('id', 'formlogin');
$form->setAttribute('action', $this->url('login'));
/*переопределим формат ошибок*/
$helper = $this->formElementErrors();
$helper->setMessageOpenFormat('<div class="alert alert-danger" role="alert">');
$helper->setMessageSeparatorString('<br/>');
$helper->setMessageCloseString('</div>');

if ($this->alertMessage){
?>
<div class="alert alert-<?=$this->alert_type?>" role="alert"><?=$this->alertMessage;?></div>
<?php 
} 
if ($this->lost_password){
?>
<div class="alert alert-warning" role="alert"><a href="#" id="lostpassword">Забыли пароль?</a></div>
<?php 
} ?>
<?=$this->form()->openTag($form);?>
  <div class="form-group row">
    <label for="login" class="col-sm-2 col-form-label">Логин</label>
    <div class="col-sm-10">
        <?php
        $name = $form->get('login');
        echo $this->formInput($name);
        echo $this->formElementErrors($name);
        ?>
    </div>
  </div>
  <div class="form-group row">
    <label for="name" class="col-sm-2 col-form-label">Пароль</label>
    <div class="col-sm-10">
        <?php
        $name = $form->get('password');
        echo $this->formElement($name);
        echo $this->formElementErrors($name);
        ?>
    </div>
  </div>
  <div class="form-group row">
    <label for="full_name" class="col-sm-2 col-form-label">Запомнить</label>
    <div class="col-sm-10">
        <?php
        $name = $form->get('remember_me');
        echo $this->formElement($name);
        echo $this->formElementErrors($name);
        ?>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-10">
              <?=$this->formInput($form->get('submit')); ?>
    </div>
  </div>
<?= $this->formElement($form->get('security')) ?>
<?= $this->form()->closeTag() ?>
</div>
<script type="text/javascript">
$("#formlogin").on("submit",function(e){
    e.preventDefault();
    $(this).ajaxSubmit({target: '#mylogin'});
});
if (<?=(int)$this->user()->getUserId()?>>0){
    window.document.location.href="<?=$this->url($this->routeNameAfterLogin)?>";
}
    
$("#lostpassword").on("click",function(e){
    $('#KabinetTab li:nth-child(3) a').tab('show');
});
$('[type=password]').hidePassword(true);
</script>

