<div id="myreset">
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('id', 'formreset');
$form->setAttribute('action', $this->url('reset-password'));

if ($this->alertMessage){
?>
<div class="alert alert-<?=$this->alert_type?>" role="alert"><?=$this->alertMessage;?></div>
<?php 
} 
?>
<?=$this->form()->openTag($form);?>
  <div class="form-group row">
    <label for="login" class="col-sm-2 col-form-label">Ваш Email</label>
    <div class="col-sm-10">
        <?php
        $name = $form->get('login');
        echo $this->formInput($name);
        echo $this->formElementErrors($name);
        ?>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-10">
              <?=$this->formInput($form->get('submit')); ?>
    </div>
  </div>
<?= $this->formElement($form->get('security')) ?>
<?= $this->form()->closeTag() ?>
</div>
<script type="text/javascript">
$("#formreset").on("submit",function(e){
    e.preventDefault();
    $(this).ajaxSubmit({target: '#myreset'});
});

</script>

