<div id="myReg">
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('id', 'formreg');
$form->setAttribute('action', $this->url('registration'));
if ($this->alertMessage){
?>
<div class="alert alert-<?=$this->alert_type?>" role="alert"><?=$this->alertMessage;?></div>
<?php 
} 
?>
<?=$this->form()->openTag($form);?>
  <div class="form-group row">
    <label for="login" class="col-sm-2 col-form-label">Логин</label>
    <div class="col-sm-10">
        <?php
        $name = $form->get('login');
        echo $this->formInput($name);
        echo $this->formElementErrors($name);
        ?>
    </div>
  </div>
  <div class="form-group row">
    <label for="name" class="col-sm-2 col-form-label">Имя</label>
    <div class="col-sm-10">
        <?php
        $name = $form->get('name');
        echo $this->formElement($name);
        echo $this->formElementErrors($name);
        ?>
    </div>
  </div>
  <div class="form-group row">
    <label for="name" class="col-sm-2 col-form-label">Фамилия</label>
    <div class="col-sm-10">
        <?php
        $name = $form->get('full_name');
        echo $this->formElement($name);
        echo $this->formElementErrors($name);
        ?>
    </div>
  </div>
  <div class="form-group row">
    <label for="name" class="col-sm-2 col-form-label">Пароль</label>
    <div class="col-sm-10">
        <?php
        $name = $form->get('password');
        echo $this->formElement($name);
        echo $this->formElementErrors($name);
        ?>
    </div>
  </div>

<div class="form-group row">
    <div class="col-sm-10">
              <?=$this->formInput($form->get('submit')); ?>
    </div>
  </div>
<?= $this->formElement($form->get('security')) ?>
<?= $this->form()->closeTag() ?>
</div>
<script type="text/javascript">
$("#formreg").on("submit",function(e){
    e.preventDefault();
    $(this).ajaxSubmit({target: '#myreg'});
});
</script>

